---
- hosts: all
  remote_user: root
  tasks:
          - name: remove amq7 root directory
            file:
                    path: "{{ amq7_root }}"
                    type: directory
                    state: absent
          - name: unmount shared store directory
            mount:
                    path: "{{ shared_dir }}"
                    fstype: nfs
                    src: "{{ shared_src }}"
                    state: absent
          - name: remove shared store directory
            file:
                    path: "{{ shared_store }}"
                    type: directory
                    state: absent
          - name: remove openwire connections
            iptables:
                    chain: INPUT
                    protocol: tcp
                    destination_port: 61616
                    jump: ACCEPT
                    state: absent
          - name: remove amqp connections
            iptables:
                    chain: INPUT
                    protocol: tcp
                    destination_port: 5672
                    jump: ACCEPT
                    state: absent

